# Generated by Django 5.0.7 on 2024-08-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categories_remove_post_subtitle_post_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorie',
            new_name='category',
        ),
    ]
